build: sf cli migration

diff --git a/.github/workflows/packaging.yml b/.github/workflows/packaging.yml
--- a/.github/workflows/packaging.yml
+++ b/.github/workflows/packaging.yml
@@ -15,21 +15,20 @@ jobs:
             # Install Salesforce CLI
             - name: 'Install Salesforce CLI'
               run: |
-                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
-                  mkdir ~/sfdx
-                  tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
-                  echo "$HOME/sfdx/bin" >> $GITHUB_PATH
-                  ~/sfdx/bin/sfdx version
+                  npm install @salesforce/cli --location=global
+                  nodeInstallPath=$(npm config get prefix)
+                  echo "$nodeInstallPath/bin" >> $GITHUB_PATH
+                  sf --version
 
-            # Checkout the code in the pull request
+            # Checkout the source code
             - name: 'Checkout source code'
-              uses: actions/checkout@v2
+              uses: actions/checkout@v4
 
             # Store secret for dev hub
             - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
               shell: bash
               run: |
-                  echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt
+                  echo ${{ secrets.DEVHUB_SFDX_URL }} > ./DEVHUB_SFDX_URL.txt
                   secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
                   if [ $secretFileSize == 1 ]; then
                       echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
@@ -38,10 +37,10 @@ jobs:
 
             # Authenticate dev hub
             - name: 'Authenticate Dev Hub'
-              run: 'sfdx force:auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d'
+              run: sf org login sfdx-url -f ./DEVHUB_SFDX_URL.txt -a devhub -d
 
             # Remove auth file
-            - name: Remove auth file
+            - name: 'Remove auth file'
               run: rm -f ./DEVHUB_SFDX_URL.txt
 
             # Add namespace to project config
@@ -70,32 +69,45 @@ jobs:
                   fi
                   exit $status
 
+            # Create package version and extract its id
+            - name: 'Create package version'
+              id: createPackageVersion
+              run: |
+                  set +e
+                  json=$(sf package version create -p Quiz -c -x -w 20 -f config/project-scratch-def.json --json)
+                  echo $json
+                  status=$(echo $json | jq '.status')
+                  if [ $status == "0" ]; then
+                      packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
+                      echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
+                  else
+                      echo "Failed to create package version"
+                  fi
+                  exit $status
+
             # Wait for package replication
-            - name: Wait for package replication
-              uses: maddox/actions/sleep@master
-              with:
-                  args: 360
+            - name: 'Wait for package replication'
+              run: sleep 360s
 
             # Create scratch org
-            - name: Create scratch org
-              run: sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -c -d 1
+            - name: 'Create scratch org'
+              run: sf org create scratch -f config/project-scratch-def.json -a scratch-org -d -y 1
 
             # Install new package in scratch org
-            - name: Install new package version in scratch org
-              run: sfdx force:package:install --package ${{ steps.create-package-version.outputs.packageVersionId }} -w 10 -u scratch-org -r
+            - name: 'Install new package version in scratch org'
+              run: sf package install -p ${{ steps.createPackageVersion.outputs.packageVersionId }} -w 10 -o scratch-org -r
 
             # Update package install link in readme
-            - name: Update package install link in readme
+            - name: 'Update package install link in readme'
               run: |
-                  packageName="${{ github.event.client_payload.packageName }}"
-                  packageVersionId="${{ steps.create-package-version.outputs.packageVersionId }}"
-                  packageLinkRegex="<a name=\"$packageName\" href=\"https:\/\/login\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-Z0-9]{18}\">"
-                  newPackageLink="<a name=\"${packageName}\" href=\"https://login.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}\">"
+                  packageVersionId="${{ steps.createPackageVersion.outputs.packageVersionId }}"
+                  packageLinkRegex="https:\/\/login\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}"
+                  newPackageLink="https://login.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}"
                   sed -E -i "s,${packageLinkRegex},${newPackageLink}," README.md
 
             # Promote package version
-            - name: Promote package version
-              run: sfdx force:package:version:promote --package ${{ steps.create-package-version.outputs.packageVersionId }} -n
+            - name: 'Promote package version'
+              run: sf package version promote --package ${{ steps.create-package-version.outputs.packageVersionId }} -n
 
             # Update sfdx-project.json and README to use only latest package version
             - name: 'Update sfdx-project.json and README'
